name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  modules:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-invoice-inventory-ext
      packages-build: codbex-invoice-inventory-ext
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-invoice-inventory-ext - ${{ inputs.release-version }}
  
        Invoice Inventory Extension - Module
  
        ## Installation
  
        ```
        npm install @codbex/codbex-invoice-inventory-ext@${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - N/A
    secrets: inherit